COMPILE_DEPS = COMPILE

osgi_jar_with_tests(
    name = "onos-sdnwise",
    visibility = ["//visibility:public"],
    deps = COMPILE_DEPS,
    #javadoc_files = glob(["src/main/javadoc/**/*"]),
    #javadoc_files_root = "src/main/javadoc",
)
